
HEADERS += ../code_base/stis/include/genericmultilevelmap.hpp \
    ../code_base/stis/include/generictype.hpp \
    ../code_base/stis/ticpp/include/ticpp.h \
    ../code_base/stis/ticpp/include/ticppapi.h \
    ../code_base/stis/ticpp/include/ticpprc.h \
    ../code_base/stis/ticpp/include/tinystr.h \
    ../code_base/stis/ticpp/include/tinyxml.h \
    ../code_base/include/core/Angle.h \
    ../code_base/include/core/average.h \
    ../code_base/include/core/CompressedFrame.h \
    ../code_base/include/core/DescriptorCreator.h \
    ../code_base/include/core/Dynamics.h \
    ../code_base/include/core/ExtendedKalmanFilter.h \
    ../code_base/include/core/FilteredDynamics.h \
    ../code_base/include/core/frame.h \
    ../code_base/include/core/GenericObject.h \
    ../code_base/include/core/GOData.h \
    ../code_base/include/core/IPAlgorithm.h \
    ../code_base/include/core/objecthandler.h \
    ../code_base/include/core/Options.h \
    ../code_base/include/core/RectangleRegion.h \
    ../code_base/include/core/SceneHandler.h \
    ../code_base/include/core/sceneobject.h \
    ../code_base/include/core/VideoBuffer.h \
    ../code_base/include/dynamic_modules/DirectedRodEMA.h \
    ../code_base/include/dynamic_modules/FreeKalman.h \
    ../code_base/include/dynamic_modules/FreeMovingAverage.h \
    ../code_base/include/dynamic_modules/NonHoloEMA.h \
    ../code_base/include/dynamic_modules/NonHoloEMA3D.h \
    ../code_base/include/dynamic_modules/NonHoloEMA_Orth.h \
    ../code_base/include/dynamic_modules/NonHoloKalman2D.h \
    ../code_base/include/dynamic_modules/NonHoloKalman2D_Orth.h \
    ../code_base/include/dynamic_modules/NonHoloKalman3D.h \
    ../code_base/include/dynamic_modules/SimpleFreeMovement.h \
    ../code_base/include/dynamic_modules/StaticDynamics.h \
    ../code_base/include/filters/ColorRangeExpansion.h \
    ../code_base/include/filters/ContrastBrightnessAdjustment.h \
    ../gui/include/Runner.h \
    ../gui/include/cvmatdisplay.h
SOURCES += ../code_base/src/core/Angle.cpp \
    ../code_base/src/core/CompressedFrame.cpp \
    ../code_base/src/core/DescriptorCreator.cpp \
    ../code_base/src/core/Dynamics.cpp \
    ../code_base/src/core/ExtendedKalmanFilter.cpp \
    ../code_base/src/core/FilteredDynamics.cpp \
    ../code_base/src/core/frame.cpp \
    ../code_base/src/core/GenericObject.cpp \
    ../code_base/src/core/GOData.cpp \
    ../code_base/src/core/IPAlgorithm.cpp \
    ../code_base/src/core/objecthandler.cpp \
    ../code_base/src/core/Options.cpp \
    ../code_base/src/core/RectangleRegion.cpp \
    ../code_base/src/core/SceneHandler.cpp \
    ../code_base/src/core/sceneobject.cpp \
    ../code_base/src/core/VideoBuffer.cpp \
    ../code_base/src/dynamic_modules/DirectedRodEMA.cpp \
    ../code_base/src/dynamic_modules/FreeKalman.cpp \
    ../code_base/src/dynamic_modules/FreeMovingAverage.cpp \
    ../code_base/src/dynamic_modules/NonHoloEMA.cpp \
    ../code_base/src/dynamic_modules/NonHoloEMA3D.cpp \
    ../code_base/src/dynamic_modules/NonHoloEMA_Orth.cpp \
    ../code_base/src/dynamic_modules/NonHoloKalman2D.cpp \
    ../code_base/src/dynamic_modules/NonHoloKalman2D_Orth.cpp \
    ../code_base/src/dynamic_modules/NonHoloKalman3D.cpp \
    ../code_base/src/dynamic_modules/SimpleFreeMovement.cpp \
    ../code_base/src/dynamic_modules/StaticDynamics.cpp \
    ../code_base/src/filters/ColorRangeExpansion.cpp \
    ../code_base/src/filters/ContrastBrightnessAdjustment.cpp \
    ../gui/src/cvmatdisplay.cpp \
    ../gui/src/main.cpp \
    ../gui/src/qtinterface.cpp \
    ../gui/src/Runner.cpp \
    ../code_base/stis/src/generictype.cpp \
    ../code_base/stis/ticpp/src/ticpp.cpp \
    ../code_base/stis/ticpp/src/tinystr.cpp \
    ../code_base/stis/ticpp/src/tinyxml.cpp \
    ../code_base/stis/ticpp/src/tinyxmlerror.cpp \
    ../code_base/stis/ticpp/src/tinyxmlparser.cpp
